### ISSUE TITLE
npm test fails TypeError: Cannot read property 'charAt' of undefined]

### ISSUE THREAD

**Issue by bluenevus** [KodeKraftwerk/reepio#28]
running on debian wheezy on ec2 using nginx reverse ssl proxy, nodejs v0.12.2.  simply did a git clone into folder masked with ../ below then npm install then npm start.  Won't start so tried npm test and error below shows

> karma start karma.conf.js

INFO [karma]: Karma v0.10.10 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [launcher]: Starting browser Firefox
INFO [launcher]: Starting browser IE
ERROR [karma]: [TypeError: Cannot read property 'charAt' of undefined]
TypeError: Cannot read property 'charAt' of undefined
    at Object.posix.isAbsolute (path.js:462:14)
    at Object.posix.normalize (path.js:444:26)
    at Object._getCommand (../reepio/node_modules/karma/lib/launchers/Base.js:106:20)
    at Object._start (../reepio/node_modules/karma/lib/launchers/Base.js:45:28)
    at Object.start (../reepio/node_modules/karma/lib/launchers/Base.js:36:10)
    at ../reepio/node_modules/karma/lib/launcher.js:38:15
    at Array.forEach (native)
    at launch (../reepio/node_modules/karma/lib/launcher.js:12:11)
    at invoke (../reepio/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (../reepio/node_modules/karma/lib/server.js:54:16)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:129:20)
    at net.js:1144:12
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
WARN [watcher]: Pattern "../reepio/public/assets/js/angular-1.2.21/angular.js" does not match any file.
WARN [watcher]: Pattern "../reepio/public/assets/js/angular-1.2.21/angular-route.js" does not match any file.
WARN [watcher]: Pattern "../reepio/public/assets/js/angular-1.2.21/angular-animate.js" does not match any file.
WARN [watcher]: Pattern "../reepio/public/assets/js/angular-1.2.21/angular-mocks.js" does not match any file.
WARN [watcher]: Pattern "../reepio/public/assets/js/angulartics-0.16.1/src/angulartics.js" does not match any file.
WARN [watcher]: Pattern "../reepio/public/assets/js/angulartics-0.16.1/src/angulartics-piwik.js" does not match any file.
WARN [watcher]: Pattern "../reepio/public/config.js" does not match any file.
npm ERR! Test failed.  See above for more details.

**Comment by bluenevus** [comment]
This is the error when trying to npm install

pre-build test failed, compiling from source...
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid tar file
    at Extract.Parse._startEntry (../reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_                    modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompres                    s/node_modules/tar/lib/parse.js:145:13)
    at Extract.Parse._process (../reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_mod                    ules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/n                    ode_modules/tar/lib/parse.js:127:12)
    at BlockStream.<anonymous> (../reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_mo                    dules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/                    node_modules/tar/lib/parse.js:47:8)
    at BlockStream.emit (events.js:107:17)
    at BlockStream._emitChunk (../reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_mod                    ules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/n                    ode_modules/tar/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (../reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules                    /imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_                    modules/tar/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (../reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modu                    les/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/no                    de_modules/tar/node_modules/fstream/lib/reader.js:255:34)
    at DirWriter.<anonymous> (/usr/share/reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modu                    les/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/no                    de_modules/tar/lib/extract.js:57:8)
    at DirWriter.emit (events.js:104:17)
    at ../reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/n                    ode_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_mod                    ules/fstream/lib/dir-writer.js:39:8

> pngquant-bin@0.3.5 postinstall ../reepio/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_m                    odules/imagemin-pngquant/node_modules/pngquant-bin
> node index.js

**Comment by bluenevus** [comment]
also doesn't work in dev mode  same error in root option or without

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "../bin/node" "../bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! reep.io@1.2.0 start: `npm install && bower install && http-server -a localhost -p 8000 -c-1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reep.io@1.2.0 start script 'npm install && bower install && http-server -a localhost -p 8000 -c-1'.
npm ERR! This is most likely a problem with the reep.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && bower install && http-server -a localhost -p 8000 -c-1
npm ERR! You can get their info via:
npm ERR!     npm owner ls reep.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ../reepio/npm-debug.log
