### ISSUE TITLE
webpack -p fails

### ISSUE THREAD

**Issue by root42** [KodeKraftwerk/reepio#41]
I am trying to build master using node v6.9.2, but am failing:

```
> reep.io@1.2.1 build-js /path/to/reepio
> webpack -p

(node:3775) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:471
    throw err;
    ^

Error: Cannot find module '/path/to/reepio/config/config.dev.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/reepio/webpack.config.js:6:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 3.2.41-042stab106.4
npm ERR! argv "/path/to/node-v6.9.2-linux-x64/bin/node" "/path/to/node-v6.9.2-linux-x64/bin/npm" "run" "build-js"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! reep.io@1.2.1 build-js: `webpack -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reep.io@1.2.1 build-js script 'webpack -p'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reep.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reep.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reep.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/reepio/npm-debug.log
```

I am at a loss what is missing here, so any pointers are welcome!

**Comment by korve** [comment]
Hey @root42 you need to create a config for your `NODE_ENV` in the config folder (e.g. config.production.js)
