### ISSUE TITLE
TypeError: "cwd" must be a string

### ISSUE THREAD

**Issue by c0d1ng** [KodeKraftwerk/reepio#47]
I was getting this error when running trying to build reepio:

```
www-data@myserver:/opt/reepio$ npm run build

> reep.io@1.2.3 build /opt/reepio
> parallelshell 'npm run build-html' 'npm run build-media' 'npm run build-js'

child_process.js:403
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:403:11)
    at exports.spawn (child_process.js:496:38)
    at /opt/reepio/node_modules/parallelshell/index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/opt/reepio/node_modules/parallelshell/index.js:100:6)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reep.io@1.2.3 build: `parallelshell 'npm run build-html' 'npm run build-media' 'npm run build-js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reep.io@1.2.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I went to the file `/opt/reepio/node_modules/parallelshell/index.js` and found the offending line. 

Changing it from `process.cwd` to `process.cwd()` fixed the issue.

**Comment by MuhammadAkif** [comment]
great thanks alot for your help :) 👍
